apiVersion: apps/v1
kind: Deployment
metadata:
  name: $DOCKER_IMAGE_NAME
  namespace: $NAMESPACE
spec:
  selector:
    matchLabels:
      app: $DOCKER_IMAGE_NAME
  template:
    metadata:
      labels:
        app: $DOCKER_IMAGE_NAME
    spec:
      containers:
      - name: $DOCKER_IMAGE_NAME
        image: $DOCKER_HUB_ID/$DOCKER_IMAGE_NAME:$BUILD_NUMBER
        imagePullPolicy: Always
        resources:
          limits:
            memory: "0"
            cpu: "0"
        ports:
        - containerPort: 8080
          name: http-port
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: $DOCKER_IMAGE_NAME
  namespace: $NAMESPACE
spec:
  selector:
    app: $DOCKER_IMAGE_NAME
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32112
  type: NodePort
